apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: new-rs
spec:
  template:
    metadata:
      name: new-rs-pod
      labels:
        env: non-prod
    spec:
      containers:
        - image: nginx
          name: testingnginx
  replicas: 5
  selector:
    matchLabels:
      env: non-prod