apiVersion: v1
kind: Pod 
metadata:
  name: sample-pod1
spec:
  containers:
  - name: demo-container
    image: muralisocial123/testing-py:1.0
    ports:
      - containerPort: 5000
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80        

