apiVersion: v1
kind: Replicaset
metadata: 
  name: first-rs
spec:
  replicas: 4
  selectors:
    matchLabels:
      app: test
  template:
    metadata:
      name: first-rs
      lables: 
        app: test  
    spec: 
      containers:
        - name: sample 
          image: nginx        